import React, { useState } from 'react';
import { Calendar, Plus, Download, FileText, Clock, User, Share2, Tag, CheckSquare, Lock } from 'lucide-react';
import { useToast } from '../shared/Toast';

export default function SocialMedia({ user, state, updateState }) {
  const toast = useToast();
  const { smmCalendar, smmQuotes, moms, clients } = state;

  // ── Role gates ────────────────────────────────────────────────────────────
  const isManager = user.role === 'Super Admin' || user.role === 'Manager';

  // Form states for Daily Timing Updates (Post Calendar)
  const [postTitle, setPostTitle] = useState('');
  const [postDate, setPostDate] = useState(new Date().toISOString().split('T')[0]);
  const [postTime, setPostTime] = useState('12:00');
  const [postPlatform, setPostPlatform] = useState('Instagram');
  const [postCaption, setPostCaption] = useState('');
  const [postStatus, setPostStatus] = useState('Scheduled');

  // Form states for SMM Quotation (manager only)
  const [quoteClient, setQuoteClient] = useState('');
  const [quoteDetails, setQuoteDetails] = useState('');
  const [quoteCost, setQuoteCost] = useState('');

  // Form states for MOM (manager only)
  const [momClient, setMomClient] = useState('');
  const [momDate, setMomDate] = useState(new Date().toISOString().split('T')[0]);
  const [momAttendees, setMomAttendees] = useState('');
  const [momPoints, setMomPoints] = useState('');
  const [momActionItems, setMomActionItems] = useState('');

  // All employees can schedule posts
  const handleAddPost = (e) => {
    e.preventDefault();
    if (!postTitle) return;

    const newPost = {
      id: `POST${Date.now()}`,
      title: postTitle,
      date: postDate,
      time: postTime,
      platform: postPlatform,
      caption: postCaption,
      status: postStatus,
      addedBy: user.name,
    };

    updateState({ smmCalendar: [...smmCalendar, newPost] });
    toast.success(`"${postTitle}" scheduled on ${postPlatform}`);
    setPostTitle('');
    setPostCaption('');
  };

  // Managers only — client-facing quotation
  const handleCreateQuote = (e) => {
    e.preventDefault();
    if (!isManager) return;
    if (!quoteClient || !quoteCost) return;

    const newQuote = {
      id: `QT${Date.now()}`,
      clientName: quoteClient,
      details: quoteDetails,
      cost: parseFloat(quoteCost),
      date: new Date().toISOString().split('T')[0],
      createdBy: user.name,
    };

    updateState({ smmQuotes: [...smmQuotes, newQuote] });

    const quoteText = `
========================================
SOCIAL MEDIA MANAGEMENT QUOTATION
========================================
Client Name: ${newQuote.clientName}
Quotation Date: ${newQuote.date}
Proposal Reference: ${newQuote.id}

Services Description:
${newQuote.details || 'General social media management, brand design, and reels compilation.'}

Total Proposed Cost: ₹${newQuote.cost.toLocaleString()} per month
Tax / GST: Inclusive

Terms:
1. 50% advance at start of campaign.
2. Invoices generated on 1st of every month.

Prepared by: ${user.name} — Social Media Department
========================================
`;
    const blob = new Blob([quoteText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SMM_Quotation_${newQuote.clientName.replace(/\s+/g, '_')}.txt`;
    a.click();

    toast.success('Quotation generated and downloaded.');
    setQuoteClient('');
    setQuoteDetails('');
    setQuoteCost('');
  };

  // Managers only — client-facing MOM
  const handleCreateMom = (e) => {
    e.preventDefault();
    if (!isManager) return;
    if (!momClient || !momPoints) return;

    const newMom = {
      id: `MOM${Date.now()}`,
      clientName: momClient,
      date: momDate,
      attendees: momAttendees,
      points: momPoints,
      actionItems: momActionItems,
      createdBy: user.name,
    };

    updateState({ moms: [...moms, newMom] });

    const momText = `
========================================
MINUTES OF MEETING (MOM)
========================================
Client Name: ${newMom.clientName}
Meeting Date: ${newMom.date}
Attendees: ${newMom.attendees || 'SMM Team & Client'}

Discussion Points:
${newMom.points}

Action Items:
${newMom.actionItems || 'No specific action items assigned.'}

Generated by: ${user.name} — Social Media Department
========================================
`;
    const blob = new Blob([momText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MOM_${newMom.clientName.replace(/\s+/g, '_')}_${newMom.date}.txt`;
    a.click();

    toast.success('MOM compiled and downloaded.');
    setMomClient('');
    setMomAttendees('');
    setMomPoints('');
    setMomActionItems('');
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Overview Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="glass-card p-6 rounded-2xl flex items-center justify-between">
          <div>
            <p className="text-sm text-slate-400">Scheduled Posts</p>
            <h3 className="text-3xl font-bold mt-1 text-glow">
              {smmCalendar.filter(p => p.status === 'Scheduled').length}
            </h3>
          </div>
          <div className="p-3 bg-violet-500/10 rounded-xl text-violet-400">
            <Calendar className="w-6 h-6" />
          </div>
        </div>

        <div className="glass-card p-6 rounded-2xl flex items-center justify-between">
          <div>
            <p className="text-sm text-slate-400">Quotations Prepared</p>
            <h3 className="text-3xl font-bold mt-1 text-glow">{smmQuotes.length}</h3>
          </div>
          <div className="p-3 bg-fuchsia-500/10 rounded-xl text-fuchsia-400">
            <FileText className="w-6 h-6" />
          </div>
        </div>

        <div className="glass-card p-6 rounded-2xl flex items-center justify-between">
          <div>
            <p className="text-sm text-slate-400">MOM Briefs</p>
            <h3 className="text-3xl font-bold mt-1 text-glow">{moms.length} Logs</h3>
          </div>
          <div className="p-3 bg-blue-500/10 rounded-xl text-blue-400">
            <Clock className="w-6 h-6" />
          </div>
        </div>
      </div>

      {/* Post Scheduler + Calendar — all roles */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="glass-panel p-6 rounded-2xl space-y-6 lg:col-span-1">
          <h2 className="text-xl font-semibold text-slate-100 flex items-center gap-2">
            <Clock className="w-5 h-5 text-violet-400" />
            Daily Timing Updates
          </h2>
          <form onSubmit={handleAddPost} className="space-y-4">
            <div>
              <label className="block text-sm text-slate-400 mb-1">Post Concept Title</label>
              <input
                type="text"
                value={postTitle}
                onChange={(e) => setPostTitle(e.target.value)}
                className="w-full glass-input p-3 rounded-xl text-sm"
                placeholder="e.g. Skincare Serum Reel"
                required
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm text-slate-400 mb-1">Date</label>
                <input type="date" value={postDate} onChange={(e) => setPostDate(e.target.value)} className="w-full glass-input p-3 rounded-xl text-sm" required />
              </div>
              <div>
                <label className="block text-sm text-slate-400 mb-1">Time</label>
                <input type="time" value={postTime} onChange={(e) => setPostTime(e.target.value)} className="w-full glass-input p-3 rounded-xl text-sm" required />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm text-slate-400 mb-1">Platform</label>
                <select value={postPlatform} onChange={(e) => setPostPlatform(e.target.value)} className="w-full glass-input p-3 rounded-xl text-sm">
                  <option value="Instagram">Instagram</option>
                  <option value="LinkedIn">LinkedIn</option>
                  <option value="Facebook">Facebook</option>
                  <option value="YouTube">YouTube</option>
                </select>
              </div>
              <div>
                <label className="block text-sm text-slate-400 mb-1">Status</label>
                <select value={postStatus} onChange={(e) => setPostStatus(e.target.value)} className="w-full glass-input p-3 rounded-xl text-sm">
                  <option value="Draft">Draft</option>
                  <option value="Scheduled">Scheduled</option>
                  <option value="Published">Published</option>
                </select>
              </div>
            </div>
            <div>
              <label className="block text-sm text-slate-400 mb-1">Post Caption</label>
              <textarea value={postCaption} onChange={(e) => setPostCaption(e.target.value)} className="w-full glass-input p-3 rounded-xl h-20 text-sm" placeholder="Include hashtags and tags..." />
            </div>
            <button type="submit" className="w-full bg-neon-gradient py-3 rounded-xl text-white font-medium shadow-md transition duration-250 flex items-center justify-center gap-2">
              <Plus className="w-5 h-5" /> Add to Content Calendar
            </button>
          </form>
        </div>

        <div className="glass-panel p-6 rounded-2xl space-y-6 lg:col-span-2">
          <h2 className="text-xl font-semibold text-slate-100 flex items-center gap-2">
            <Calendar className="w-5 h-5 text-fuchsia-400" />
            Interactive Content Calendar
          </h2>
          <div className="space-y-4 max-h-[420px] overflow-y-auto pr-1">
            {smmCalendar.length === 0 ? (
              <p className="text-slate-400 text-center py-10">No items in the content calendar yet.</p>
            ) : (
              smmCalendar.map(post => (
                <div key={post.id} className="glass-card p-4 rounded-xl flex items-start justify-between gap-4 border-l-4 border-l-violet-500">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <span className="text-xs bg-violet-500/10 text-violet-400 px-2.5 py-0.5 rounded-full font-medium">{post.platform}</span>
                      <span className="text-xs text-slate-400 flex items-center gap-1"><Clock className="w-3 h-3" /> {post.date} @ {post.time}</span>
                    </div>
                    <h4 className="font-semibold text-slate-200">{post.title}</h4>
                    <p className="text-sm text-slate-400 line-clamp-2 italic">{post.caption}</p>
                    {post.addedBy && <p className="text-xs text-slate-600">Added by {post.addedBy}</p>}
                  </div>
                  <div>
                    <span className={`text-xs px-2.5 py-1 rounded-full font-medium ${
                      post.status === 'Published' ? 'bg-emerald-500/10 text-emerald-400' :
                      post.status === 'Scheduled' ? 'bg-indigo-500/10 text-indigo-400' :
                      'bg-amber-500/10 text-amber-400'
                    }`}>{post.status}</span>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Quotation + MOM — managers only */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="glass-panel p-6 rounded-2xl space-y-6">
          <h2 className="text-xl font-semibold text-slate-100 flex items-center gap-2">
            <Share2 className="w-5 h-5 text-violet-400" />
            Plan Proposal (SMM Quotation)
            {!isManager && <span className="ml-auto flex items-center gap-1 text-xs text-slate-500 font-normal"><Lock className="w-3.5 h-3.5" /> Manager only</span>}
          </h2>
          {isManager ? (
            <form onSubmit={handleCreateQuote} className="space-y-4">
              <div>
                <label className="block text-sm text-slate-400 mb-1">Target Client Name</label>
                <input type="text" value={quoteClient} onChange={(e) => setQuoteClient(e.target.value)} className="w-full glass-input p-3 rounded-xl" placeholder="e.g. Luna Fashion" required />
              </div>
              <div>
                <label className="block text-sm text-slate-400 mb-1">Proposal Service Details</label>
                <textarea value={quoteDetails} onChange={(e) => setQuoteDetails(e.target.value)} className="w-full glass-input p-3 rounded-xl h-24 text-sm" placeholder="e.g. 15 Reels, 10 Static Grid Posts..." required />
              </div>
              <div>
                <label className="block text-sm text-slate-400 mb-1">Proposed Monthly Retainer (₹)</label>
                <input type="number" value={quoteCost} onChange={(e) => setQuoteCost(e.target.value)} className="w-full glass-input p-3 rounded-xl" placeholder="80000" required />
              </div>
              <button type="submit" className="w-full bg-violet-600 hover:bg-violet-700 py-3 rounded-xl text-white font-medium transition flex items-center justify-center gap-2">
                <Download className="w-5 h-5" /> Generate & Download Quotation
              </button>
            </form>
          ) : (
            <div className="flex flex-col items-center justify-center py-10 text-center gap-3 border border-dashed border-slate-800 rounded-xl">
              <Lock className="w-8 h-8 text-slate-600" />
              <p className="text-sm text-slate-500">Only managers can generate client quotations.</p>
            </div>
          )}
        </div>

        <div className="glass-panel p-6 rounded-2xl space-y-6">
          <h2 className="text-xl font-semibold text-slate-100 flex items-center gap-2">
            <FileText className="w-5 h-5 text-fuchsia-400" />
            Minutes of Meeting (MOM)
            {!isManager && <span className="ml-auto flex items-center gap-1 text-xs text-slate-500 font-normal"><Lock className="w-3.5 h-3.5" /> Manager only</span>}
          </h2>
          {isManager ? (
            <form onSubmit={handleCreateMom} className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-1">Client Name</label>
                  <input type="text" value={momClient} onChange={(e) => setMomClient(e.target.value)} className="w-full glass-input p-3 rounded-xl text-sm" placeholder="Aura Cosmetics" required />
                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-1">Meeting Date</label>
                  <input type="date" value={momDate} onChange={(e) => setMomDate(e.target.value)} className="w-full glass-input p-3 rounded-xl text-sm" required />
                </div>
              </div>
              <div>
                <label className="block text-sm text-slate-400 mb-1">Attendees</label>
                <input type="text" value={momAttendees} onChange={(e) => setMomAttendees(e.target.value)} className="w-full glass-input p-3 rounded-xl text-sm" placeholder="Aarav (Paid Ads), Priya (Client CEO)" required />
              </div>
              <div>
                <label className="block text-sm text-slate-400 mb-1">Key Discussion Points</label>
                <textarea value={momPoints} onChange={(e) => setMomPoints(e.target.value)} className="w-full glass-input p-3 rounded-xl h-20 text-sm" placeholder="List major items discussed..." required />
              </div>
              <div>
                <label className="block text-sm text-slate-400 mb-1">Action Items / Assignments</label>
                <textarea value={momActionItems} onChange={(e) => setMomActionItems(e.target.value)} className="w-full glass-input p-3 rounded-xl h-20 text-sm" placeholder="e.g. Sneha to build landing page..." />
              </div>
              <button type="submit" className="w-full bg-fuchsia-600 hover:bg-fuchsia-700 py-3 rounded-xl text-white font-medium transition flex items-center justify-center gap-2">
                <Download className="w-5 h-5" /> Compile & Download MOM
              </button>
            </form>
          ) : (
            <div className="flex flex-col items-center justify-center py-10 text-center gap-3 border border-dashed border-slate-800 rounded-xl">
              <Lock className="w-8 h-8 text-slate-600" />
              <p className="text-sm text-slate-500">Only managers can compile client meeting minutes.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}